# ================================================================
# NewClient1 — Go Dockerfile
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

# ── STAGE 1: Builder ─────────────────────────────────────────────
FROM golang:20-alpine AS builder

WORKDIR /app

# Copy go module files first for layer caching
COPY go.mod go.sum ./
RUN go mod download

# Copy source and build
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags="-w -s" \
    -o /app/server \
    ./cmd/server

# ── STAGE 2: Production (distroless for Go — smallest possible image) ──
FROM gcr.io/distroless/static-debian12 AS production

WORKDIR /app

# Copy binary from builder
COPY --from=builder /app/server .

# Distroless runs as nonroot by default (uid 65532)
USER nonroot:nonroot

EXPOSE 3000

CMD ["/app/server"]
