# ================================================================
# hamza-corp — dev — AWS Infrastructure
# Generated by Opt IT Backstage
# DO NOT EDIT MANUALLY — changes will be overwritten on next run
# ================================================================

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # Uncomment and configure backend for remote state:
  # backend "s3" {
  #   bucket = "hamza-corp-dev-tfstate"
  #   key    = "infrastructure/terraform.tfstate"
  #   region = "us-east-1"
  # }
}

provider "aws" {
  region = var.aws_region
}

# ────────────────────────────────────────────────────────────────
# VPC
# $Not selected$
# ────────────────────────────────────────────────────────────────

$

# ────────────────────────────────────────────────────────────────
# SECURITY GROUPS
# $Not selected$
# ────────────────────────────────────────────────────────────────

$

# ────────────────────────────────────────────────────────────────
# EC2
# $Not selected$
# ────────────────────────────────────────────────────────────────

$

# ────────────────────────────────────────────────────────────────
# S3
# $Not selected$
# ────────────────────────────────────────────────────────────────

$

# ────────────────────────────────────────────────────────────────
# RDS
# $Not selected$
# ────────────────────────────────────────────────────────────────

$
