# ================================================================
# new-client — staging — AWS Infrastructure
# Generated by Opt IT Backstage
# DO NOT EDIT MANUALLY — changes will be overwritten on next run
# ================================================================

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # Uncomment and configure backend for remote state:
  # backend "s3" {
  #   bucket = "new-client-staging-tfstate"
  #   key    = "infrastructure/terraform.tfstate"
  #   region = "us-east-1"
  # }
}

provider "aws" {
  region = var.aws_region
}

# ────────────────────────────────────────────────────────────────
# VPC
# $Provisioned$
# ────────────────────────────────────────────────────────────────

$
module "vpc" {
  source = "./modules/vpc"

  client_name        = var.client_name
  environment        = var.environment
  module_version     = "1.0.0"
  aws_region         = var.aws_region
  vpc_cidr           = var.vpc_cidr
  enable_nat_gateway = var.environment == "prod" ? true : false
}

module "subnets" {
  source = "./modules/subnets"

  client_name         = var.client_name
  environment         = var.environment
  module_version      = "1.0.0"
  aws_region          = var.aws_region
  vpc_id              = module.vpc.vpc_id
  vpc_cidr            = module.vpc.vpc_cidr
  internet_gateway_id = module.vpc.internet_gateway_id
  nat_gateway_id      = module.vpc.nat_gateway_id
}
$

# ────────────────────────────────────────────────────────────────
# SECURITY GROUPS
# $Provisioned$
# ────────────────────────────────────────────────────────────────

$
module "security_groups" {
  source = "./modules/security-groups"

  client_name    = var.client_name
  environment    = var.environment
  module_version = "1.0.0"
  vpc_id         = module.vpc.vpc_id
  vpc_cidr       = module.vpc.vpc_cidr
  rds_port       = var.rds_engine == "mysql" ? 3306 : 5432
}
$

# ────────────────────────────────────────────────────────────────
# EC2
# $Provisioned$
# ────────────────────────────────────────────────────────────────

$
module "iam" {
  source = "./modules/iam-baseline"

  client_name        = var.client_name
  environment        = var.environment
  module_version     = "1.0.0"
  $
}

module "ec2" {
  source = "./modules/ec2"

  client_name        = var.client_name
  environment        = var.environment
  module_version     = "1.0.0"
  aws_region         = var.aws_region
  subnet_id          = module.subnets.private_subnet_ids[0]
  security_group_ids = [module.security_groups.web_security_group_id]
  instance_type      = var.ec2_instance_type
}
$

# ────────────────────────────────────────────────────────────────
# S3
# $Not selected$
# ────────────────────────────────────────────────────────────────

$

# ────────────────────────────────────────────────────────────────
# RDS
# $Not selected$
# ────────────────────────────────────────────────────────────────

$
