# ================================================================
# new-client — staging — Outputs
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

$
output "vpc_id" {
  description = "VPC ID"
  value       = module.vpc.vpc_id
}
$

$
output "ec2_instance_id" {
  description = "EC2 instance ID"
  value       = module.ec2.instance_id
}

output "ec2_private_ip" {
  description = "EC2 private IP"
  value       = module.ec2.instance_private_ip
}
$

$

$
