# ================================================================
# hamza-corp — dev — Outputs
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

$
output "vpc_id" {
  description = "VPC ID"
  value       = module.vpc.vpc_id
}
$

$
output "ec2_instance_id" {
  description = "EC2 instance ID"
  value       = module.ec2.instance_id
}

output "ec2_private_ip" {
  description = "EC2 private IP"
  value       = module.ec2.instance_private_ip
}
$

$
output "s3_bucket_name" {
  description = "S3 bucket name"
  value       = module.s3.bucket_id
}

output "s3_bucket_arn" {
  description = "S3 bucket ARN"
  value       = module.s3.bucket_arn
}
$

$
