# ================================================================
# NewClient1 — dev — Variables
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

variable "client_name" {
  description = "Client name"
  type        = string
  default     = "NewClient1"
}

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "dev"
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

$
variable "vpc_cidr" {
  description = "VPC CIDR block"
  type        = string
  default     = "10.0.0.0/16"
}
$

$
variable "ec2_instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t3.small"
}
$

$
